services:
    catalogdb:
        image: postgres:17.4
        
    basketdb:
        image: postgres:17.4

    catalog.api:
        image: ${DOCKER_REGISTRY-}catalogapi
        build:
          context: .
          dockerfile: Services/Catalog.API/Dockerfile

volumes:
        postgres_catalog:
        postgres_basket: