services:
  catalogdb:
    container_name: catalogdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=CatalogDB
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_catalog:/var/lib/postgresql

  basketdb:
    container_name: basketdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=BasketDB
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - postgres_catalog:/var/lib/postgresql
  
  distributedcache:
    container_name: distributedcache
    restart: always
    ports:
        - "6379:6379"
  
  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=catalogdb;Port=5432;Database=CatalogDB;User Id=postgres;Password=postgres;Include Error Detail=true

      # MAC Users.
      # - ASPNETCORE_Kestrel__Certificates__Default__Password=pass
      # - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx

    depends_on:
        - catalogdb
    ports:
      - "6000:8080"
      - "6060:8081"
    volumes:
      # MAC Users.
      # - ~/.microsoft/usersecrets:/home/app/.microsoft/usersecrets:ro
      # - ~/.aspnet/https:/https:ro

      # Windows Users.
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro


  basket.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
        # Since we're inside Docker network we should use default Port 5432.
      - ConnectionStrings__Database=Server=basketdb;Port=5432;Database=BasketDB;User Id=postgres;Password=postgres;Include Error Detail=true
      - ConnectionStrings__Redis=distributedcache:6379
      - GrpcSettings__DiscountUrl=https://discount.grpc:8081

      # MAC Users.
      # - ASPNETCORE_Kestrel__Certificates__Default__Password=pass
      # - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    depends_on:
      - basketdb
      - distributedcache
      - discount.grpc
    ports:
      - "6001:8080"
      - "6061:8081"
    volumes:
      # Windows Users.
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

      # MAC Users.
      # - ~/.microsoft/usersecrets:/home/app/.microsoft/usersecrets:ro
      # - ~/.aspnet/https:/https:ro


  discount.grpc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Data Source=discountdb

      # MAC Users.
      # - ASPNETCORE_Kestrel__Certificates__Default__Password=pass
      # - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    ports:
      - "6002:8080"
      - "6062:8081"
    volumes:
      # Windows Users.
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      
      # MAC Users.
      # - ~/.microsoft/usersecrets:/home/app/.microsoft/usersecrets:ro
      # - ~/.aspnet/https:/https:ro